server:
  port: 0
spring:
  kafka:
    bootstrap-server: localhost:9092
  datasource:
    url: jdbc:postgresql://viaduct.proxy.rlwy.net:11135/railway
    username: postgres
    password: -gE4DCa15E1AfGeC66CF2gBD*4*bdE*a
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
    locations: classpath:db-migration
